alter table se_user
    alter column se_user_id add generated by default as identity;

select setval('se_user_se_user_id_seq', (select max(se_user_id) + 1 from se_user));


alter table post
    alter column post_id add generated by default as identity;

select setval('post_post_id_seq', (select max(post_id) + 1 from post));


alter table comment
    alter column comment_id add generated by default as identity;

select setval('comment_comment_id_seq', (select max(comment_id) + 1 from comment));


alter table badge
    alter column badge_id add generated by default as identity;

select setval('badge_badge_id_seq', (select max(badge_id) + 1 from badge));


alter table vote
    alter column vote_id add generated by default as identity;

select setval('vote_vote_id_seq', (select max(vote_id) + 1 from vote));


alter table post_link
    alter column post_link_id add generated by default as identity;

select setval('post_link_post_link_id_seq', (select max(post_link_id) + 1 from post_link));


alter table post_history
    alter column post_history_id add generated by default as identity;

select setval('post_history_post_history_id_seq', (select max(post_history_id) + 1 from post_history));
